routes/web.php
<?php

use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('template');
});

// SPECIAL ROUTE JUST FOR DEMO
Route::get('/switch/{user}', [ 'as' => 'switch_user', function($user) {

	// We don't need a controller for this...
	auth()->loginUsingId($user);
	return redirect()->back();

} ]);

// For this demo, we are going to need a user, and pretend to be authenticated (althoug normally we would use login...)

// so I'm going to seed a temp user and then just login as him ALL the time :D

// THIS IS WHERE RESOURCES SHINE!!!!!

Route::resource('recipes', 'RecipeController'); // Using resource gives us ALL crud routes :D LOVE IT, USE IT... It's amazing!


// We can daisy chain resources together by a . prefix...

Route::resource('recipes.comments', 'RecipeCommentController'); // and let's create the controller

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    // Some of the things I do here aren't necessary, but they make for easier updating when things change

    // We need to setup the inverse relationships here...

    const DB_TABLE = 'recipes';

    const ATTR_ID = 'id';
    const ATTR_NAME = 'name';
    const ATTR_DESCRIPTION = 'description';

    protected $primaryKey = self::ATTR_ID;

    protected $fillable = [
    	self::ATTR_NAME,
    	self::ATTR_DESCRIPTION
    ];
    
    public function getId()
    {
    	return $this->{self::ATTR_ID};
    }

    public function getName()
    {
    	return $this->{self::ATTR_NAME};
    }

    public function getDescription()
    {
    	return $this->{self::ATTR_DESCRIPTION};
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function comments()
    {
        return $this->hasMany(RecipeComment::class, RecipeComment::ATTR_RECIPE_ID); // Has Many Comment Class via 'recipe_id'
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Recipe;
use Illuminate\Http\Request;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Show some recipes...

        $recipes = Recipe::all();

        // compact() another AMAZING function... accepts 'string','string','string'...

        // converts to...
        /*
            compact('recipes') =>
            [
                'recipes' => $recipes
            ]

            string must match variable name...
        */

        return view('recipes.index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Create Form

        return view('recipes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $recipe = Recipe::find($id);

        return view('recipes.show', compact('recipe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $recipe = Recipe::find($id);

        return view('recipes.edit', compact('recipe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Recipe::destroy($id);

        return view('recipe.index');
    }
}

resources/views/recipes/comments/create.blade.php
<div class="new_comment">

	<p>Commenting As: {{ auth()->user()->getName() }}</p>

	<form method="POST" action="{{ route('recipes.comments.store', $recipe->getId()) }}">

		<!-- I never use php and I use ajax / vue -->
		{{ csrf_field() }}

		<textarea name="body"></textarea>

		<input type="submit" class="btn btn-primary" value="Add Comment" />

	</form>

</div>

resources/views/recipes/comments/index.blade.php
<!-- Now we need to list comments -->

<!-- Now you're probably saying... WHOA WTF!!! None of that exists... 

	You're absolutely right...
-->

<!-- NO ERRORS NOW... yay... but what if there are no comments??? -->


<!-- Now the question was, in regarding to deleting your OWN comments -->

<!-- So with this, we will need a way to "switch" users -->

<div class="comment_list">

	@if($recipe->getComments()->count()) <!-- IF we have comments -->

		@foreach($recipe->getComments() as $comment) <!-- SHOW THEM -->

		<div class="comment">

			<h2>{{ $comment->getAuthor()->name }} says...</h2>
			<p>{{ $comment->getBody() }}</p>

			<!-- We don't want to show this button for EVERYONE... -->
			<!-- Only for the User who wrote it... -->
			@if ($comment->isOwner()) <!-- Create new method on the COMMENT class -->
				<form action="{{ route('recipes.comments.destroy', [ 'recipe' => $recipe->getId(), 'comment' => $comment->getId() ]) }}" method="POST">
					{{ csrf_field() }}
					@method('DELETE')
					<button class="btn btn-sm btn-danger">Delete Comment</button>					
				</form>
			@endif

		</div>

		@endforeach

	@else

		<p>There are no comments... BE THE FIRST!</p>

	@endif

</div>